ncids_trans.settings:
  type: theme_settings
  label: 'NCIDS Transitional Theme Settings'
  mapping:
    features:
      type: config_object
      mapping:
        node_user_picture:
          type: boolean
          label: 'User pictures in posts'
        comment_user_picture:
          type: boolean
          label: 'User pictures in comments'
        comment_user_verification:
          type: boolean
          label: 'User verification status in comments'
        favicon:
          type: integer
          label: 'Shortcut icon'
    logo:
      type: config_object
      mapping:
        use_default:
          type: integer
          label: 'Use the logo supplied by the theme'
    favicon:
      type: config_object
      mapping:
        use_default:
          type: integer
          label: 'Use the logo supplied by the theme'
    has_translations:
      type: integer
      label: 'Has Translations'
    mobile_levels_to_display:
      type: integer
      label: 'Mobile navigation levels to display'
