name: OCPL Configuration Management Standards Check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  commitlint_remote:
    uses: nciocpl/.github/.github/workflows/ocpl_cm_standards_check.yml@workflow/v4
    with:
      config_ref: workflow/v4
